spring:
  application:
    name: eureka-client-api-gateway
    profiles:
      active: dev
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8765


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instace_id:${random.value}}


  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
